aws_region        = "us-east-1"
key_name          = "jenkins-key"
bucket_name       = "my-terraform-state-bucket-123456"
vpc_cidr          = "10.0.0.0/16"
subnet_cidr       = "10.0.0.0/24"
availability_zone = "us-east-1a"
